// lib/models/gallery_component_catalog.dart
//
// Single source of truth for every component shown in the developer gallery.
//
// The gallery (`lib/modules/dev/component_gallery_screen.dart`) documents the
// whole reusable card library, but only a handful of those cards were wired to
// the layout interpreter, so `MangaHomeScreen` and `WatchExtensionHomeScreen`
// could not render them. This catalog gives every public, reusable gallery
// component a stable JSON id, a renderer family and a loading preview, so the
// declarative layout JSON can select any of them.
//
// The ids are stored in `GalleryComponentDescriptor.id` and are always written
// to layout JSON in kebab-case (for example `movie-details`). The matching
// widgets live in `lib/modules/watch/home/gallery_component_renderer.dart`.

import 'package:watchtower/models/layout_component_registry.dart';

/// Renderer families implemented for gallery components.
///
/// Each family maps a set of JSON component ids to an adapter that builds the
/// real card from extension-home content. Unlike
/// [LayoutComponentRenderer] (which keeps the legacy extension rails compact),
/// this enum exposes the full gallery card library.
enum GalleryComponentFamily {
  richMedia,
  streaming,
  collections,
  episodes,
  ranking,
  mangaChapter,
  mangaVolume,
  mangaGenre,
  mangaReader,
  mangaUniverse,
  mangaStats,
  homeHero,
  // Reuse the existing extension renderers for the shared rails.
  posterRail,
  spotlight,
  banner,
  ranked,
  landscape,
  grid,
  swipe,
}

/// The JSON-facing definition of one gallery component.
class GalleryComponentDescriptor {
  const GalleryComponentDescriptor({
    required this.id,
    required this.className,
    required this.label,
    required this.category,
    required this.description,
    required this.renderer,
    required this.loadingPreview,
    this.aliases = const [],
    this.selectable = true,
  });

  /// Stable identifier written to layout JSON (kebab-case).
  final String id;

  /// Main Dart class the gallery previews for this component.
  final String className;
  final String label;
  final String category;
  final String description;
  final GalleryComponentFamily renderer;
  final LayoutComponentLoadingPreview loadingPreview;
  final List<String> aliases;

  /// Compatibility-only descriptors stay valid in existing JSON but are not
  /// suggested as new choices.
  final bool selectable;
}

/// Registry of every gallery component that the layout interpreter can render.
class GalleryComponentCatalog {
  GalleryComponentCatalog._();
  static const descriptors = <GalleryComponentDescriptor>[
    GalleryComponentDescriptor(
      id: 'movie-details',
      className: 'MovieDetailsCard',
      label: 'Carte détails complète',
      category: 'CARTES RICHES',
      description: 'Note, casting et actions rapides',
      renderer: GalleryComponentFamily.richMedia,
      loadingPreview: LayoutComponentLoadingPreview.row,
    ),
    GalleryComponentDescriptor(
      id: 'movie-detail',
      className: 'MovieDetailCard',
      label: 'Carte détail compacte',
      category: 'CARTES RICHES',
      description: 'Image en arrière-plan plein cadre',
      renderer: GalleryComponentFamily.richMedia,
      loadingPreview: LayoutComponentLoadingPreview.row,
    ),
    GalleryComponentDescriptor(
      id: 'expanded-movie',
      className: 'ExpandedMovieCard',
      label: 'Carte extensible',
      category: 'CARTES RICHES',
      description: 'Infos supplémentaires dépliables',
      renderer: GalleryComponentFamily.richMedia,
      loadingPreview: LayoutComponentLoadingPreview.row,
    ),
    GalleryComponentDescriptor(
      id: 'expandable-movie',
      className: 'ExpandableMovieCard',
      label: 'Carte extensible auto',
      category: 'CARTES RICHES',
      description: 'Le tap étend/replie la carte',
      renderer: GalleryComponentFamily.richMedia,
      loadingPreview: LayoutComponentLoadingPreview.row,
    ),
    GalleryComponentDescriptor(
      id: 'interactive-movie',
      className: 'InteractiveMovieCard',
      label: 'Carte interactive',
      category: 'CARTES RICHES',
      description: 'Survol/clic révèle les actions rapides',
      renderer: GalleryComponentFamily.richMedia,
      loadingPreview: LayoutComponentLoadingPreview.row,
    ),
    GalleryComponentDescriptor(
      id: 'hover-movie',
      className: 'HoverMovieCard',
      label: 'Carte effet survol',
      category: 'CARTES RICHES',
      description: 'La fiche glisse par-dessus le poster',
      renderer: GalleryComponentFamily.richMedia,
      loadingPreview: LayoutComponentLoadingPreview.row,
    ),
    GalleryComponentDescriptor(
      id: 'movie-quick-view',
      className: 'MovieQuickView',
      label: 'Aperçu rapide',
      category: 'CARTES RICHES',
      description: 'Aperçu rapide avec fond image et fermer',
      renderer: GalleryComponentFamily.richMedia,
      loadingPreview: LayoutComponentLoadingPreview.row,
    ),
    GalleryComponentDescriptor(
      id: 'media-quick-view',
      className: 'MediaQuickView',
      label: 'Aperçu rapide média',
      category: 'CARTES RICHES',
      description: 'Alias générique de MovieQuickView',
      renderer: GalleryComponentFamily.richMedia,
      loadingPreview: LayoutComponentLoadingPreview.row,
    ),
    GalleryComponentDescriptor(
      id: 'movie-preview',
      className: 'MoviePreview',
      label: 'Aperçu poster',
      category: 'CARTES RICHES',
      description: 'Poster + note + bouton play',
      renderer: GalleryComponentFamily.richMedia,
      loadingPreview: LayoutComponentLoadingPreview.row,
    ),
    GalleryComponentDescriptor(
      id: 'media-preview',
      className: 'MediaPreview',
      label: 'Aperçu poster média',
      category: 'CARTES RICHES',
      description: 'Alias générique de MoviePreview',
      renderer: GalleryComponentFamily.richMedia,
      loadingPreview: LayoutComponentLoadingPreview.row,
    ),
    GalleryComponentDescriptor(
      id: 'movie-details-modal',
      className: 'MovieDetailsModal',
      label: 'Modale détails',
      category: 'CARTES RICHES',
      description: 'Feuille modale détails rapides',
      renderer: GalleryComponentFamily.richMedia,
      loadingPreview: LayoutComponentLoadingPreview.row,
    ),
    GalleryComponentDescriptor(
      id: 'media-details-modal',
      className: 'MediaDetailsModal',
      label: 'Modale détails média',
      category: 'CARTES RICHES',
      description: 'Alias générique de MovieDetailsModal',
      renderer: GalleryComponentFamily.richMedia,
      loadingPreview: LayoutComponentLoadingPreview.row,
    ),
    GalleryComponentDescriptor(
      id: 'continue-watching',
      className: 'ContinueWatchingCard',
      label: 'Reprise de lecture',
      category: 'STREAMING & PROGRESSION',
      description: 'Visuel, progression et actions de reprise',
      renderer: GalleryComponentFamily.streaming,
      loadingPreview: LayoutComponentLoadingPreview.row,
    ),
    GalleryComponentDescriptor(
      id: 'continue-watching-item',
      className: 'ContinueWatchingItem',
      label: 'Élément compact à reprendre',
      category: 'STREAMING & PROGRESSION',
      description: 'Ligne compacte pour une liste à reprendre',
      renderer: GalleryComponentFamily.streaming,
      loadingPreview: LayoutComponentLoadingPreview.row,
    ),
    GalleryComponentDescriptor(
      id: 'resume-watching',
      className: 'ResumeWatchingCard',
      label: 'Carte de reprise rapide',
      category: 'STREAMING & PROGRESSION',
      description: 'Chip, play et barre de progression',
      renderer: GalleryComponentFamily.streaming,
      loadingPreview: LayoutComponentLoadingPreview.row,
    ),
    GalleryComponentDescriptor(
      id: 'recently-watched',
      className: 'RecentlyWatchedCard',
      label: 'Récemment regardés',
      category: 'STREAMING & PROGRESSION',
      description: 'Panneau à trois posters + voir tout',
      renderer: GalleryComponentFamily.streaming,
      loadingPreview: LayoutComponentLoadingPreview.row,
    ),
    GalleryComponentDescriptor(
      id: 'watch-again',
      className: 'WatchAgainCard',
      label: 'Carte à revoir',
      category: 'STREAMING & PROGRESSION',
      description: 'Chip « À revoir » et bouton Revoir',
      renderer: GalleryComponentFamily.streaming,
      loadingPreview: LayoutComponentLoadingPreview.row,
    ),
    GalleryComponentDescriptor(
      id: 'now-playing',
      className: 'NowPlayingCard',
      label: 'Lecture en cours',
      category: 'STREAMING & PROGRESSION',
      description: 'Large visuel, badges HD et actions',
      renderer: GalleryComponentFamily.streaming,
      loadingPreview: LayoutComponentLoadingPreview.row,
    ),
    GalleryComponentDescriptor(
      id: 'up-next',
      className: 'UpNextCard',
      label: 'Prochain épisode',
      category: 'STREAMING & PROGRESSION',
      description: 'Compte à rebours et rappel',
      renderer: GalleryComponentFamily.streaming,
      loadingPreview: LayoutComponentLoadingPreview.row,
    ),
    GalleryComponentDescriptor(
      id: 'next-episode',
      className: 'NextEpisodeCard',
      label: 'Épisode suivant',
      category: 'STREAMING & PROGRESSION',
      description: 'Dispo imminente, play et progression',
      renderer: GalleryComponentFamily.streaming,
      loadingPreview: LayoutComponentLoadingPreview.row,
    ),
    GalleryComponentDescriptor(
      id: 'episode',
      className: 'EpisodeCard',
      label: 'Liste d\\',
      category: 'STREAMING & PROGRESSION',
      description: 'Saison dépliable, épisodes courant/verrouillé',
      renderer: GalleryComponentFamily.streaming,
      loadingPreview: LayoutComponentLoadingPreview.row,
    ),
    GalleryComponentDescriptor(
      id: 'season',
      className: 'SeasonCard',
      label: 'Carte de saison',
      category: 'STREAMING & PROGRESSION',
      description: 'Voir la saison + sélecteur S1…S4',
      renderer: GalleryComponentFamily.streaming,
      loadingPreview: LayoutComponentLoadingPreview.row,
    ),
    GalleryComponentDescriptor(
      id: 'series-episode',
      className: 'SeriesEpisodeCard',
      label: 'Série + épisode compact',
      category: 'STREAMING & PROGRESSION',
      description: 'Rangée horizontale avec play et chevron',
      renderer: GalleryComponentFamily.streaming,
      loadingPreview: LayoutComponentLoadingPreview.row,
    ),
    GalleryComponentDescriptor(
      id: 'watch-progress',
      className: 'WatchProgressCard',
      label: 'Progression visuelle',
      category: 'STREAMING & PROGRESSION',
      description: 'Barre de progression et pourcentage',
      renderer: GalleryComponentFamily.streaming,
      loadingPreview: LayoutComponentLoadingPreview.row,
    ),
    GalleryComponentDescriptor(
      id: 'progress-media',
      className: 'ProgressMediaCard',
      label: 'Barre de progression',
      category: 'STREAMING & PROGRESSION',
      description: 'Style barre + bouton play',
      renderer: GalleryComponentFamily.streaming,
      loadingPreview: LayoutComponentLoadingPreview.row,
    ),
    GalleryComponentDescriptor(
      id: 'progress-media-card-percent',
      className: 'ProgressMediaCard(percent)',
      label: 'Barre de progression (%)',
      category: 'STREAMING & PROGRESSION',
      description: 'Pourcentage affiché à droite',
      renderer: GalleryComponentFamily.streaming,
      loadingPreview: LayoutComponentLoadingPreview.row,
    ),
    GalleryComponentDescriptor(
      id: 'progress-media-card-chip',
      className: 'ProgressMediaCard(chip)',
      label: 'Barre de progression (chip)',
      category: 'STREAMING & PROGRESSION',
      description: 'Pastille de pourcentage sur la vignette',
      renderer: GalleryComponentFamily.streaming,
      loadingPreview: LayoutComponentLoadingPreview.row,
    ),
    GalleryComponentDescriptor(
      id: 'collection',
      className: 'CollectionCard',
      label: 'Collection de films/séries',
      category: 'COLLECTIONS & FRANCHISES',
      description: 'Univers principal + tuiles d’autres collections',
      renderer: GalleryComponentFamily.collections,
      loadingPreview: LayoutComponentLoadingPreview.collections,
    ),
    GalleryComponentDescriptor(
      id: 'movie-collection',
      className: 'MovieCollectionCard',
      label: 'Collection de films',
      category: 'COLLECTIONS & FRANCHISES',
      description: 'Trilogie / saga + posters latéraux',
      renderer: GalleryComponentFamily.collections,
      loadingPreview: LayoutComponentLoadingPreview.collections,
    ),
    GalleryComponentDescriptor(
      id: 'franchise',
      className: 'FranchiseCard',
      label: 'Franchise',
      category: 'COLLECTIONS & FRANCHISES',
      description: 'Franchise spécifique, titre en grand',
      renderer: GalleryComponentFamily.collections,
      loadingPreview: LayoutComponentLoadingPreview.collections,
    ),
    GalleryComponentDescriptor(
      id: 'saga',
      className: 'SagaCard',
      label: 'Saga',
      category: 'COLLECTIONS & FRANCHISES',
      description: 'Saga littéraire ou film',
      renderer: GalleryComponentFamily.collections,
      loadingPreview: LayoutComponentLoadingPreview.collections,
    ),
    GalleryComponentDescriptor(
      id: 'studio',
      className: 'StudioCard',
      label: 'Studio de production',
      category: 'COLLECTIONS & FRANCHISES',
      description: 'Studio + tuiles d’autres studios',
      renderer: GalleryComponentFamily.collections,
      loadingPreview: LayoutComponentLoadingPreview.collections,
    ),
    GalleryComponentDescriptor(
      id: 'network',
      className: 'NetworkCard',
      label: 'Réseau TV',
      category: 'COLLECTIONS & FRANCHISES',
      description: 'Réseau / plateforme + tuiles voisines',
      renderer: GalleryComponentFamily.collections,
      loadingPreview: LayoutComponentLoadingPreview.collections,
    ),
    GalleryComponentDescriptor(
      id: 'genre',
      className: 'GenreCard',
      label: 'Genre de contenu',
      category: 'COLLECTIONS & FRANCHISES',
      description: 'Genre + rangées de genres voisins',
      renderer: GalleryComponentFamily.collections,
      loadingPreview: LayoutComponentLoadingPreview.collections,
    ),
    GalleryComponentDescriptor(
      id: 'actor',
      className: 'ActorCard',
      label: 'Acteur / Actrice',
      category: 'COLLECTIONS & FRANCHISES',
      description: 'Portrait, âge et filmographie',
      renderer: GalleryComponentFamily.collections,
      loadingPreview: LayoutComponentLoadingPreview.collections,
    ),
    GalleryComponentDescriptor(
      id: 'director',
      className: 'DirectorCard',
      label: 'Réalisateur',
      category: 'COLLECTIONS & FRANCHISES',
      description: 'Portrait et films marquants',
      renderer: GalleryComponentFamily.collections,
      loadingPreview: LayoutComponentLoadingPreview.collections,
    ),
    GalleryComponentDescriptor(
      id: 'character',
      className: 'CharacterCard',
      label: 'Personnage',
      category: 'COLLECTIONS & FRANCHISES',
      description: 'Fiche personnage + autres rôles',
      renderer: GalleryComponentFamily.collections,
      loadingPreview: LayoutComponentLoadingPreview.collections,
    ),
    GalleryComponentDescriptor(
      id: 'related-media',
      className: 'RelatedMediaCard',
      label: 'Contenu lié',
      category: 'COLLECTIONS & FRANCHISES',
      description: 'Même univers, même équipe…',
      renderer: GalleryComponentFamily.collections,
      loadingPreview: LayoutComponentLoadingPreview.collections,
    ),
    GalleryComponentDescriptor(
      id: 'similar-media',
      className: 'SimilarMediaCard',
      label: 'Contenus similaires',
      category: 'COLLECTIONS & FRANCHISES',
      description: 'Même genre, même ambiance',
      renderer: GalleryComponentFamily.collections,
      loadingPreview: LayoutComponentLoadingPreview.collections,
    ),
    GalleryComponentDescriptor(
      id: 'trending',
      className: 'TrendingCard',
      label: 'Contenu tendance',
      category: 'COLLECTIONS & FRANCHISES',
      description: 'Top actuel avec rangs',
      renderer: GalleryComponentFamily.collections,
      loadingPreview: LayoutComponentLoadingPreview.collections,
    ),
    GalleryComponentDescriptor(
      id: 'popular',
      className: 'PopularCard',
      label: 'Contenu populaire',
      category: 'COLLECTIONS & FRANCHISES',
      description: 'Le plus de vues',
      renderer: GalleryComponentFamily.collections,
      loadingPreview: LayoutComponentLoadingPreview.collections,
    ),
    GalleryComponentDescriptor(
      id: 'top-rated',
      className: 'TopRatedCard',
      label: 'Mieux notés',
      category: 'COLLECTIONS & FRANCHISES',
      description: 'Notes IMDb / TMDB',
      renderer: GalleryComponentFamily.collections,
      loadingPreview: LayoutComponentLoadingPreview.collections,
    ),
    GalleryComponentDescriptor(
      id: 'ranked-media',
      className: 'RankedMediaCard',
      label: 'Classement Top 10',
      category: 'COLLECTIONS & FRANCHISES',
      description: 'Top 10 / top 50 avec grands numéros',
      renderer: GalleryComponentFamily.collections,
      loadingPreview: LayoutComponentLoadingPreview.collections,
    ),
    GalleryComponentDescriptor(
      id: 'numbered',
      className: 'NumberedCard',
      label: 'Carte numérotée',
      category: 'COLLECTIONS & FRANCHISES',
      description: 'Top 10 compact, sans en-tête',
      renderer: GalleryComponentFamily.collections,
      loadingPreview: LayoutComponentLoadingPreview.collections,
    ),
    GalleryComponentDescriptor(
      id: 'featured',
      className: 'FeaturedCard',
      label: 'Contenu à la une',
      category: 'COLLECTIONS & FRANCHISES',
      description: 'Grand visuel + points de carrousel',
      renderer: GalleryComponentFamily.collections,
      loadingPreview: LayoutComponentLoadingPreview.collections,
    ),
    GalleryComponentDescriptor(
      id: 'spotlight-card',
      className: 'SpotlightCard',
      label: 'Coup de projecteur',
      category: 'COLLECTIONS & FRANCHISES',
      description: 'Événement, nouveauté',
      renderer: GalleryComponentFamily.collections,
      loadingPreview: LayoutComponentLoadingPreview.collections,
    ),
    GalleryComponentDescriptor(
      id: 'recommendation',
      className: 'RecommendationCard',
      label: 'Recommandations',
      category: 'COLLECTIONS & FRANCHISES',
      description: 'Parce que vous avez aimé…',
      renderer: GalleryComponentFamily.collections,
      loadingPreview: LayoutComponentLoadingPreview.collections,
    ),
    GalleryComponentDescriptor(
      id: 'carousel-card',
      className: 'CarouselCard',
      label: 'Carrousel d’univers',
      category: 'COLLECTIONS & FRANCHISES',
      description: 'Collections / univers avec flèches',
      renderer: GalleryComponentFamily.collections,
      loadingPreview: LayoutComponentLoadingPreview.collections,
    ),
    GalleryComponentDescriptor(
      id: 'universe',
      className: 'UniverseCard',
      label: 'Univers (alias)',
      category: 'COLLECTIONS & FRANCHISES',
      description: 'Alias générique de FranchiseCard',
      renderer: GalleryComponentFamily.collections,
      loadingPreview: LayoutComponentLoadingPreview.collections,
    ),
    GalleryComponentDescriptor(
      id: 'category-card',
      className: 'CategoryCard',
      label: 'Catégorie (alias)',
      category: 'COLLECTIONS & FRANCHISES',
      description: 'Alias générique de GenreCard',
      renderer: GalleryComponentFamily.collections,
      loadingPreview: LayoutComponentLoadingPreview.collections,
    ),
    GalleryComponentDescriptor(
      id: 'cast',
      className: 'CastCard',
      label: 'Casting (alias)',
      category: 'COLLECTIONS & FRANCHISES',
      description: 'Alias générique de ActorCard',
      renderer: GalleryComponentFamily.collections,
      loadingPreview: LayoutComponentLoadingPreview.collections,
    ),
    GalleryComponentDescriptor(
      id: 'compact-episode',
      className: 'CompactEpisodeCard',
      label: 'Épisode (format compact)',
      category: 'ÉPISODES & SAISONS',
      description: 'EpisodeCard — carte d\\',
      renderer: GalleryComponentFamily.episodes,
      loadingPreview: LayoutComponentLoadingPreview.row,
    ),
    GalleryComponentDescriptor(
      id: 'episode-thumbnail',
      className: 'EpisodeThumbnail',
      label: 'Miniature d\\',
      category: 'ÉPISODES & SAISONS',
      description: 'Grand format 16:9 avec play et HD',
      renderer: GalleryComponentFamily.episodes,
      loadingPreview: LayoutComponentLoadingPreview.row,
    ),
    GalleryComponentDescriptor(
      id: 'episode-preview',
      className: 'EpisodePreviewCard',
      label: 'Épisode avec aperçu',
      category: 'ÉPISODES & SAISONS',
      description: 'Visuel + description + progression',
      renderer: GalleryComponentFamily.episodes,
      loadingPreview: LayoutComponentLoadingPreview.row,
    ),
    GalleryComponentDescriptor(
      id: 'episode-list-item',
      className: 'EpisodeListItem',
      label: 'Liste d\\',
      category: 'ÉPISODES & SAISONS',
      description: 'Élément de liste : vu ▵ / play / verrouillé',
      renderer: GalleryComponentFamily.episodes,
      loadingPreview: LayoutComponentLoadingPreview.row,
    ),
    GalleryComponentDescriptor(
      id: 'season-detail',
      className: 'SeasonDetailCard',
      label: 'Carte de saison',
      category: 'ÉPISODES & SAISONS',
      description: 'SeasonCard — visuel, stats et description',
      renderer: GalleryComponentFamily.episodes,
      loadingPreview: LayoutComponentLoadingPreview.row,
    ),
    GalleryComponentDescriptor(
      id: 'featured-episode',
      className: 'FeaturedEpisodeCard',
      label: 'Épisode de série mis en avant',
      category: 'ÉPISODES & SAISONS',
      description: 'SeriesEpisodeCard — poster avec chip de saison',
      renderer: GalleryComponentFamily.episodes,
      loadingPreview: LayoutComponentLoadingPreview.row,
    ),
    GalleryComponentDescriptor(
      id: 'next-episode-hero',
      className: 'NextEpisodeHeroCard',
      label: 'Prochain épisode (héros)',
      category: 'ÉPISODES & SAISONS',
      description: 'NextEpisodeCard — grand visuel et chip',
      renderer: GalleryComponentFamily.episodes,
      loadingPreview: LayoutComponentLoadingPreview.row,
    ),
    GalleryComponentDescriptor(
      id: 'latest-episode',
      className: 'LatestEpisodeCard',
      label: 'Dernier épisode ajouté',
      category: 'ÉPISODES & SAISONS',
      description: 'Badge Nouveau + bouton Voir la série',
      renderer: GalleryComponentFamily.episodes,
      loadingPreview: LayoutComponentLoadingPreview.row,
    ),
    GalleryComponentDescriptor(
      id: 'season-selector',
      className: 'SeasonSelectorCard',
      label: 'Sélecteur de saison',
      category: 'ÉPISODES & SAISONS',
      description: 'Poster + chips S1-S5 + épisodes',
      renderer: GalleryComponentFamily.episodes,
      loadingPreview: LayoutComponentLoadingPreview.row,
    ),
    GalleryComponentDescriptor(
      id: 'series-episode-list',
      className: 'SeriesEpisodeListCard',
      label: 'Liste compacte de série',
      category: 'ÉPISODES & SAISONS',
      description: 'SeriesEpisodeCard (liste compacte)',
      renderer: GalleryComponentFamily.episodes,
      loadingPreview: LayoutComponentLoadingPreview.row,
    ),
    GalleryComponentDescriptor(
      id: 'episode-progress',
      className: 'EpisodeProgressCard',
      label: 'Progression de visionnage',
      category: 'ÉPISODES & SAISONS',
      description: 'WatchProgressCard — épisode en cours',
      renderer: GalleryComponentFamily.episodes,
      loadingPreview: LayoutComponentLoadingPreview.row,
    ),
    GalleryComponentDescriptor(
      id: 'media-progress',
      className: 'MediaProgressCard',
      label: 'Média avec barre de progression',
      category: 'ÉPISODES & SAISONS',
      description: 'ProgressMediaCard — temps restant et HD',
      renderer: GalleryComponentFamily.episodes,
      loadingPreview: LayoutComponentLoadingPreview.row,
    ),
    GalleryComponentDescriptor(
      id: 'up-next-compact',
      className: 'UpNextCompactCard',
      label: 'Prochain épisode (compact)',
      category: 'ÉPISODES & SAISONS',
      description: 'UpNextCard — format paysage compact',
      renderer: GalleryComponentFamily.episodes,
      loadingPreview: LayoutComponentLoadingPreview.row,
    ),
    GalleryComponentDescriptor(
      id: 'season-episode',
      className: 'SeasonEpisodeCard',
      label: 'Épisode avec info saison',
      category: 'ÉPISODES & SAISONS',
      description: 'EpisodeCard (avec saison) et genres',
      renderer: GalleryComponentFamily.episodes,
      loadingPreview: LayoutComponentLoadingPreview.row,
    ),
    GalleryComponentDescriptor(
      id: 'series-banner',
      className: 'SeriesBannerCard',
      label: 'Bannière de série',
      category: 'ÉPISODES & SAISONS',
      description: 'Bannière large avec infos et note',
      renderer: GalleryComponentFamily.episodes,
      loadingPreview: LayoutComponentLoadingPreview.row,
    ),
    GalleryComponentDescriptor(
      id: 'episode-carousel',
      className: 'EpisodeCarousel',
      label: 'Carrousel d\\',
      category: 'ÉPISODES & SAISONS',
      description: 'Mini-cartes, sélection et flèches',
      renderer: GalleryComponentFamily.episodes,
      loadingPreview: LayoutComponentLoadingPreview.row,
    ),
    GalleryComponentDescriptor(
      id: 'season-banner',
      className: 'SeasonBannerCard',
      label: 'Saison (style horizontal)',
      category: 'ÉPISODES & SAISONS',
      description: 'SeasonCard horizontale avec note',
      renderer: GalleryComponentFamily.episodes,
      loadingPreview: LayoutComponentLoadingPreview.row,
    ),
    GalleryComponentDescriptor(
      id: 'episode-list',
      className: 'EpisodeListCard',
      label: 'Liste avec vignettes',
      category: 'ÉPISODES & SAISONS',
      description: 'Épisodes avec vignettes 16:9',
      renderer: GalleryComponentFamily.episodes,
      loadingPreview: LayoutComponentLoadingPreview.row,
    ),
    GalleryComponentDescriptor(
      id: 'series-grid',
      className: 'SeriesGridCard',
      label: 'Grille de saisons',
      category: 'ÉPISODES & SAISONS',
      description: 'Grille d\\',
      renderer: GalleryComponentFamily.episodes,
      loadingPreview: LayoutComponentLoadingPreview.row,
    ),
    GalleryComponentDescriptor(
      id: 'top-movies',
      className: 'TopMoviesCard',
      label: 'Top 10 Films du moment',
      category: 'CLASSEMENTS & TOP 10',
      description: 'Films les plus populaires',
      renderer: GalleryComponentFamily.ranking,
      loadingPreview: LayoutComponentLoadingPreview.ranked,
    ),
    GalleryComponentDescriptor(
      id: 'top-series',
      className: 'TopSeriesCard',
      label: 'Top 10 Séries du moment',
      category: 'CLASSEMENTS & TOP 10',
      description: 'Séries les plus regardées',
      renderer: GalleryComponentFamily.ranking,
      loadingPreview: LayoutComponentLoadingPreview.ranked,
    ),
    GalleryComponentDescriptor(
      id: 'top-anime',
      className: 'TopAnimeCard',
      label: 'Top 10 Animés',
      category: 'CLASSEMENTS & TOP 10',
      description: 'Animés les plus populaires',
      renderer: GalleryComponentFamily.ranking,
      loadingPreview: LayoutComponentLoadingPreview.ranked,
    ),
    GalleryComponentDescriptor(
      id: 'top-by-genre',
      className: 'TopByGenreCard',
      label: 'Top 10 par genre',
      category: 'CLASSEMENTS & TOP 10',
      description: 'Tuiles de genres 1-10',
      renderer: GalleryComponentFamily.ranking,
      loadingPreview: LayoutComponentLoadingPreview.ranked,
    ),
    GalleryComponentDescriptor(
      id: 'top-by-country',
      className: 'TopByCountryCard',
      label: 'Top 10 par pays',
      category: 'CLASSEMENTS & TOP 10',
      description: 'Tuiles de pays 1-10',
      renderer: GalleryComponentFamily.ranking,
      loadingPreview: LayoutComponentLoadingPreview.ranked,
    ),
    GalleryComponentDescriptor(
      id: 'global-ranking',
      className: 'GlobalRankingCard',
      label: 'Classement global',
      category: 'CLASSEMENTS & TOP 10',
      description: 'Top 20 tous contenus confondus',
      renderer: GalleryComponentFamily.ranking,
      loadingPreview: LayoutComponentLoadingPreview.ranked,
    ),
    GalleryComponentDescriptor(
      id: 'top-rated-ranking',
      className: 'TopRatedRankingCard',
      label: 'Top 10 des plus notés',
      category: 'CLASSEMENTS & TOP 10',
      description: 'Notes des utilisateurs',
      renderer: GalleryComponentFamily.ranking,
      loadingPreview: LayoutComponentLoadingPreview.ranked,
    ),
    GalleryComponentDescriptor(
      id: 'trending-ranking',
      className: 'TrendingRankingCard',
      label: 'Top 10 tendances',
      category: 'CLASSEMENTS & TOP 10',
      description: 'Ce qui fait le plus parler',
      renderer: GalleryComponentFamily.ranking,
      loadingPreview: LayoutComponentLoadingPreview.ranked,
    ),
    GalleryComponentDescriptor(
      id: 'top-by-decade',
      className: 'TopByDecadeCard',
      label: 'Top 10 par décennie',
      category: 'CLASSEMENTS & TOP 10',
      description: 'Tuiles de décennies',
      renderer: GalleryComponentFamily.ranking,
      loadingPreview: LayoutComponentLoadingPreview.ranked,
    ),
    GalleryComponentDescriptor(
      id: 'must-watch',
      className: 'MustWatchCard',
      label: 'Top 10 à voir absolument',
      category: 'CLASSEMENTS & TOP 10',
      description: 'Sélection des incontournables',
      renderer: GalleryComponentFamily.ranking,
      loadingPreview: LayoutComponentLoadingPreview.ranked,
    ),
    GalleryComponentDescriptor(
      id: 'manga-chapter',
      className: 'MangaChapterCard',
      label: 'Carte chapitre',
      category: 'MANGA & LECTURE',
      description: 'Carte d\\',
      renderer: GalleryComponentFamily.mangaChapter,
      loadingPreview: LayoutComponentLoadingPreview.row,
    ),
    GalleryComponentDescriptor(
      id: 'manga-chapter-release',
      className: 'MangaChapterReleaseCard',
      label: 'Sorties de chapitres',
      category: 'MANGA & LECTURE',
      description: 'Nouveaux chapitres',
      renderer: GalleryComponentFamily.mangaChapter,
      loadingPreview: LayoutComponentLoadingPreview.row,
    ),
    GalleryComponentDescriptor(
      id: 'manga-chapter-list',
      className: 'MangaChapterListCard',
      label: 'Liste des chapitres',
      category: 'MANGA & LECTURE',
      description: 'Liste complète des chapitres',
      renderer: GalleryComponentFamily.mangaChapter,
      loadingPreview: LayoutComponentLoadingPreview.row,
    ),
    GalleryComponentDescriptor(
      id: 'manga-chapter-group',
      className: 'MangaChapterGroupCard',
      label: 'Arc de chapitres',
      category: 'MANGA & LECTURE',
      description: 'Groupement par arc ou partie',
      renderer: GalleryComponentFamily.mangaChapter,
      loadingPreview: LayoutComponentLoadingPreview.row,
    ),
    GalleryComponentDescriptor(
      id: 'manga-latest-release',
      className: 'MangaLatestReleaseCard',
      label: 'Dernières sorties',
      category: 'MANGA & LECTURE',
      description: 'Dernières sorties avec aperçu',
      renderer: GalleryComponentFamily.mangaChapter,
      loadingPreview: LayoutComponentLoadingPreview.row,
    ),
    GalleryComponentDescriptor(
      id: 'manga-release-timeline',
      className: 'MangaReleaseTimelineCard',
      label: 'Calendrier des sorties',
      category: 'MANGA & LECTURE',
      description: 'Frise des sorties (calendrier)',
      renderer: GalleryComponentFamily.mangaChapter,
      loadingPreview: LayoutComponentLoadingPreview.row,
    ),
    GalleryComponentDescriptor(
      id: 'manga-chapter-volume',
      className: 'MangaChapterVolumeCard',
      label: 'Carte volume',
      category: 'MANGA & LECTURE',
      description: 'Carte d\\',
      renderer: GalleryComponentFamily.mangaChapter,
      loadingPreview: LayoutComponentLoadingPreview.row,
    ),
    GalleryComponentDescriptor(
      id: 'manga-chapter-badge',
      className: 'MangaChapterBadge',
      label: 'Badges de chapitre',
      category: 'MANGA & LECTURE',
      description: 'Badge de chapitre / statut',
      renderer: GalleryComponentFamily.mangaChapter,
      loadingPreview: LayoutComponentLoadingPreview.row,
    ),
    GalleryComponentDescriptor(
      id: 'manga-chapter-range',
      className: 'MangaChapterRangeCard',
      label: 'Plage de chapitres',
      category: 'MANGA & LECTURE',
      description: 'Plage de chapitres (ex : 100-110)',
      renderer: GalleryComponentFamily.mangaChapter,
      loadingPreview: LayoutComponentLoadingPreview.row,
    ),
    GalleryComponentDescriptor(
      id: 'manga-chapter-timeline',
      className: 'MangaChapterTimelineCard',
      label: 'Chronologie de l’arc',
      category: 'MANGA & LECTURE',
      description: 'Chronologie des chapitres',
      renderer: GalleryComponentFamily.mangaChapter,
      loadingPreview: LayoutComponentLoadingPreview.row,
    ),
    GalleryComponentDescriptor(
      id: 'manga-new-chapter',
      className: 'MangaNewChapterCard',
      label: 'Nouveau chapitre',
      category: 'MANGA & LECTURE',
      description: 'Mise en avant d\\',
      renderer: GalleryComponentFamily.mangaChapter,
      loadingPreview: LayoutComponentLoadingPreview.row,
    ),
    GalleryComponentDescriptor(
      id: 'manga-chapter-progress',
      className: 'MangaChapterProgressCard',
      label: 'Progression de lecture',
      category: 'MANGA & LECTURE',
      description: 'Progression de lecture par chapitre',
      renderer: GalleryComponentFamily.mangaChapter,
      loadingPreview: LayoutComponentLoadingPreview.row,
    ),
    GalleryComponentDescriptor(
      id: 'manga-chapter-next',
      className: 'MangaChapterNextCard',
      label: 'Prochain chapitre',
      category: 'MANGA & LECTURE',
      description: 'Prochain chapitre à venir',
      renderer: GalleryComponentFamily.mangaChapter,
      loadingPreview: LayoutComponentLoadingPreview.row,
    ),
    GalleryComponentDescriptor(
      id: 'manga-chapter-search',
      className: 'MangaChapterSearchCard',
      label: 'Recherche de chapitre',
      category: 'MANGA & LECTURE',
      description: 'Recherche de chapitre spécifique',
      renderer: GalleryComponentFamily.mangaChapter,
      loadingPreview: LayoutComponentLoadingPreview.row,
    ),
    GalleryComponentDescriptor(
      id: 'manga-volume',
      className: 'MangaVolumeCard',
      label: 'Volume populaire',
      category: 'MANGA & LECTURE',
      description: 'Poster + tome + note + chip VF',
      renderer: GalleryComponentFamily.mangaVolume,
      loadingPreview: LayoutComponentLoadingPreview.row,
    ),
    GalleryComponentDescriptor(
      id: 'manga-volume-list',
      className: 'MangaVolumeListCard',
      label: 'Liste de volumes',
      category: 'MANGA & LECTURE',
      description: 'Parcourir tous les tomes d\\',
      renderer: GalleryComponentFamily.mangaVolume,
      loadingPreview: LayoutComponentLoadingPreview.row,
    ),
    GalleryComponentDescriptor(
      id: 'manga-volume-preview',
      className: 'MangaVolumePreviewCard',
      label: 'Aperçu des volumes',
      category: 'MANGA & LECTURE',
      description: 'Couvertures superposées + plage de tomes',
      renderer: GalleryComponentFamily.mangaVolume,
      loadingPreview: LayoutComponentLoadingPreview.row,
    ),
    GalleryComponentDescriptor(
      id: 'manga-special-edition',
      className: 'MangaSpecialEditionCard',
      label: 'Édition spéciale',
      category: 'MANGA & LECTURE',
      description: 'Éditions collector, limitées et variantes',
      renderer: GalleryComponentFamily.mangaVolume,
      loadingPreview: LayoutComponentLoadingPreview.row,
    ),
    GalleryComponentDescriptor(
      id: 'manga-format',
      className: 'MangaFormatCard',
      label: 'Format d\\',
      category: 'MANGA & LECTURE',
      description: 'Tankōbon, Omnibus, Intégrale…',
      renderer: GalleryComponentFamily.mangaVolume,
      loadingPreview: LayoutComponentLoadingPreview.row,
    ),
    GalleryComponentDescriptor(
      id: 'manga-edition-language',
      className: 'MangaEditionLanguageCard',
      label: 'Éditions par langue',
      category: 'MANGA & LECTURE',
      description: 'Disponibilités VO/VF par langue',
      renderer: GalleryComponentFamily.mangaVolume,
      loadingPreview: LayoutComponentLoadingPreview.row,
    ),
    GalleryComponentDescriptor(
      id: 'manga-collection-tracker',
      className: 'MangaCollectionTrackerCard',
      label: 'Suivi de collection',
      category: 'MANGA & LECTURE',
      description: 'Bibliothèque de tomes avec progression',
      renderer: GalleryComponentFamily.mangaVolume,
      loadingPreview: LayoutComponentLoadingPreview.row,
    ),
    GalleryComponentDescriptor(
      id: 'manga-upcoming-volume',
      className: 'MangaUpcomingVolumeCard',
      label: 'Volumes à venir',
      category: 'MANGA & LECTURE',
      description: 'Prochaines sorties de volumes',
      renderer: GalleryComponentFamily.mangaVolume,
      loadingPreview: LayoutComponentLoadingPreview.row,
    ),
    GalleryComponentDescriptor(
      id: 'manga-genres',
      className: 'MangaGenresCard',
      label: 'Grille de genres',
      category: 'MANGA & LECTURE',
      description: 'Genres avec compteurs de mangas',
      renderer: GalleryComponentFamily.mangaGenre,
      loadingPreview: LayoutComponentLoadingPreview.categoryPills,
    ),
    GalleryComponentDescriptor(
      id: 'manga-demographics',
      className: 'MangaDemographicsCard',
      label: 'Démographies',
      category: 'MANGA & LECTURE',
      description: 'Shōnen, Shōjo, Seinen, Josei…',
      renderer: GalleryComponentFamily.mangaGenre,
      loadingPreview: LayoutComponentLoadingPreview.categoryPills,
    ),
    GalleryComponentDescriptor(
      id: 'manga-themes',
      className: 'MangaThemesCard',
      label: 'Thèmes',
      category: 'MANGA & LECTURE',
      description: 'École, Isekai, Reincarnation…',
      renderer: GalleryComponentFamily.mangaGenre,
      loadingPreview: LayoutComponentLoadingPreview.categoryPills,
    ),
    GalleryComponentDescriptor(
      id: 'manga-universe-showcase',
      className: 'MangaUniverseShowcaseCard',
      label: 'Collections / Univers',
      category: 'MANGA & LECTURE',
      description: 'Sagas et univers incontournables',
      renderer: GalleryComponentFamily.mangaGenre,
      loadingPreview: LayoutComponentLoadingPreview.categoryPills,
    ),
    GalleryComponentDescriptor(
      id: 'manga-tags',
      className: 'MangaTagsCard',
      label: 'Tags colorés',
      category: 'MANGA & LECTURE',
      description: 'Tags d\\',
      renderer: GalleryComponentFamily.mangaGenre,
      loadingPreview: LayoutComponentLoadingPreview.categoryPills,
    ),
    GalleryComponentDescriptor(
      id: 'manga-languages',
      className: 'MangaLanguagesCard',
      label: 'Langues / Traductions',
      category: 'MANGA & LECTURE',
      description: 'Langues, équipes de scanlation, statuts',
      renderer: GalleryComponentFamily.mangaGenre,
      loadingPreview: LayoutComponentLoadingPreview.categoryPills,
    ),
    GalleryComponentDescriptor(
      id: 'manga-publishers',
      className: 'MangaPublishersCard',
      label: 'Éditeurs & Publications',
      category: 'MANGA & LECTURE',
      description: 'Shueisha, Kodansha, Viz Media…',
      renderer: GalleryComponentFamily.mangaGenre,
      loadingPreview: LayoutComponentLoadingPreview.categoryPills,
    ),
    GalleryComponentDescriptor(
      id: 'manga-language-news',
      className: 'MangaLanguageNewsCard',
      label: 'Nouveautés par langue',
      category: 'MANGA & LECTURE',
      description: 'Derniers ajouts par langue',
      renderer: GalleryComponentFamily.mangaGenre,
      loadingPreview: LayoutComponentLoadingPreview.categoryPills,
    ),
    GalleryComponentDescriptor(
      id: 'manga-reader',
      className: 'MangaReaderCard',
      label: 'Accès lecture',
      category: 'MANGA & LECTURE',
      description: 'Accès rapide à la lecture d\\',
      renderer: GalleryComponentFamily.mangaReader,
      loadingPreview: LayoutComponentLoadingPreview.row,
    ),
    GalleryComponentDescriptor(
      id: 'manga-page',
      className: 'MangaPageCard',
      label: 'Page de manga',
      category: 'MANGA & LECTURE',
      description: 'Une page en haute qualité',
      renderer: GalleryComponentFamily.mangaReader,
      loadingPreview: LayoutComponentLoadingPreview.row,
    ),
    GalleryComponentDescriptor(
      id: 'manga-page-preview',
      className: 'MangaPagePreviewCard',
      label: 'Aperçu des pages',
      category: 'MANGA & LECTURE',
      description: 'Navigation rapide entre planches',
      renderer: GalleryComponentFamily.mangaReader,
      loadingPreview: LayoutComponentLoadingPreview.row,
    ),
    GalleryComponentDescriptor(
      id: 'manga-page-strip',
      className: 'MangaPageStripCard',
      label: 'Bandeau de pages',
      category: 'MANGA & LECTURE',
      description: 'Lecture en bandeau (strip)',
      renderer: GalleryComponentFamily.mangaReader,
      loadingPreview: LayoutComponentLoadingPreview.row,
    ),
    GalleryComponentDescriptor(
      id: 'manga-double-page',
      className: 'MangaDoublePageCard',
      label: 'Double page',
      category: 'MANGA & LECTURE',
      description: 'Affichage double page écran large',
      renderer: GalleryComponentFamily.mangaReader,
      loadingPreview: LayoutComponentLoadingPreview.row,
    ),
    GalleryComponentDescriptor(
      id: 'manga-reading-mode',
      className: 'MangaReadingModeCard',
      label: 'Mode de lecture',
      category: 'MANGA & LECTURE',
      description: 'Classique, double page, vertical, scroll',
      renderer: GalleryComponentFamily.mangaReader,
      loadingPreview: LayoutComponentLoadingPreview.row,
    ),
    GalleryComponentDescriptor(
      id: 'manga-reading-direction',
      className: 'MangaReadingDirectionCard',
      label: 'Direction de lecture',
      category: 'MANGA & LECTURE',
      description: 'De droite à gauche / de gauche à droite',
      renderer: GalleryComponentFamily.mangaReader,
      loadingPreview: LayoutComponentLoadingPreview.row,
    ),
    GalleryComponentDescriptor(
      id: 'manga-reader-settings',
      className: 'MangaReaderSettingsCard',
      label: 'Réglages du reader',
      category: 'MANGA & LECTURE',
      description: 'Texte, police, luminosité, qualité',
      renderer: GalleryComponentFamily.mangaReader,
      loadingPreview: LayoutComponentLoadingPreview.row,
    ),
    GalleryComponentDescriptor(
      id: 'manga-page-progress',
      className: 'MangaPageProgressCard',
      label: 'Anneau de progression',
      category: 'MANGA & LECTURE',
      description: 'Avancement global de la lecture',
      renderer: GalleryComponentFamily.mangaReader,
      loadingPreview: LayoutComponentLoadingPreview.row,
    ),
    GalleryComponentDescriptor(
      id: 'manga-reading-progress',
      className: 'MangaReadingProgressCard',
      label: 'Progression chapitre',
      category: 'MANGA & LECTURE',
      description: 'Progression du chapitre avec marque-page',
      renderer: GalleryComponentFamily.mangaReader,
      loadingPreview: LayoutComponentLoadingPreview.row,
    ),
    GalleryComponentDescriptor(
      id: 'manga-chapter-navigation',
      className: 'MangaChapterNavigationCard',
      label: 'Navigation chapitres',
      category: 'MANGA & LECTURE',
      description: 'Chapitre précédent / suivant',
      renderer: GalleryComponentFamily.mangaReader,
      loadingPreview: LayoutComponentLoadingPreview.row,
    ),
    GalleryComponentDescriptor(
      id: 'manga-quick-access',
      className: 'MangaQuickAccessCard',
      label: 'Accès rapide',
      category: 'MANGA & LECTURE',
      description: 'Reprise + favoris + raccourcis',
      renderer: GalleryComponentFamily.mangaReader,
      loadingPreview: LayoutComponentLoadingPreview.row,
    ),
    GalleryComponentDescriptor(
      id: 'manga-reader-floating',
      className: 'MangaReaderFloatingCard',
      label: 'Contrôles flottants',
      category: 'MANGA & LECTURE',
      description: 'Barre d\\',
      renderer: GalleryComponentFamily.mangaReader,
      loadingPreview: LayoutComponentLoadingPreview.row,
    ),
    GalleryComponentDescriptor(
      id: 'manga-reader-chapter-list',
      className: 'MangaReaderChapterListCard',
      label: 'Liste chapitres (reader)',
      category: 'MANGA & LECTURE',
      description: 'Filtres Tous / Lu / Non lu',
      renderer: GalleryComponentFamily.mangaReader,
      loadingPreview: LayoutComponentLoadingPreview.row,
    ),
    GalleryComponentDescriptor(
      id: 'manga-reader-history',
      className: 'MangaReaderHistoryCard',
      label: 'Historique de lecture',
      category: 'MANGA & LECTURE',
      description: 'Derniers chapitres lus',
      renderer: GalleryComponentFamily.mangaReader,
      loadingPreview: LayoutComponentLoadingPreview.row,
    ),
    GalleryComponentDescriptor(
      id: 'manga-relation-type',
      className: 'MangaRelationTypeCard',
      label: 'Types de relations',
      category: 'MANGA & LECTURE',
      description: 'Main story, Préquelle, Suite, Spin-off…',
      renderer: GalleryComponentFamily.mangaUniverse,
      loadingPreview: LayoutComponentLoadingPreview.row,
    ),
    GalleryComponentDescriptor(
      id: 'manga-universe-timeline',
      className: 'MangaUniverseTimelineCard',
      label: 'Univers & Timeline',
      category: 'MANGA & LECTURE',
      description: 'Mondes et chronologies des séries',
      renderer: GalleryComponentFamily.mangaUniverse,
      loadingPreview: LayoutComponentLoadingPreview.row,
    ),
    GalleryComponentDescriptor(
      id: 'manga-linked-series',
      className: 'MangaLinkedSeriesCard',
      label: 'Séries liées',
      category: 'MANGA & LECTURE',
      description: 'Univers partagés (Naruto → Boruto…)',
      renderer: GalleryComponentFamily.mangaUniverse,
      loadingPreview: LayoutComponentLoadingPreview.row,
    ),
    GalleryComponentDescriptor(
      id: 'manga-relation-list',
      className: 'MangaRelationListCard',
      label: 'Relations spécifiques',
      category: 'MANGA & LECTURE',
      description: 'Crossover, remake, sequel/préquel…',
      renderer: GalleryComponentFamily.mangaUniverse,
      loadingPreview: LayoutComponentLoadingPreview.row,
    ),
    GalleryComponentDescriptor(
      id: 'manga-same-universe',
      className: 'MangaSameUniverseCard',
      label: 'Œuvres du même univers',
      category: 'MANGA & LECTURE',
      description: 'Toutes les œuvres d\\',
      renderer: GalleryComponentFamily.mangaUniverse,
      loadingPreview: LayoutComponentLoadingPreview.row,
    ),
    GalleryComponentDescriptor(
      id: 'manga-universe-chronology',
      className: 'MangaUniverseChronologyCard',
      label: 'Chronologie de l\\',
      category: 'MANGA & LECTURE',
      description: 'Timeline des événements',
      renderer: GalleryComponentFamily.mangaUniverse,
      loadingPreview: LayoutComponentLoadingPreview.row,
    ),
    GalleryComponentDescriptor(
      id: 'manga-franchise-universes',
      className: 'MangaFranchiseUniversesCard',
      label: 'Univers par franchise',
      category: 'MANGA & LECTURE',
      description: 'Grandes franchises et leurs mondes',
      renderer: GalleryComponentFamily.mangaUniverse,
      loadingPreview: LayoutComponentLoadingPreview.row,
    ),
    GalleryComponentDescriptor(
      id: 'manga-character-relations',
      className: 'MangaCharacterRelationsCard',
      label: 'Relations entre personnages',
      category: 'MANGA & LECTURE',
      description: 'Amis, rivaux, amour, famille…',
      renderer: GalleryComponentFamily.mangaUniverse,
      loadingPreview: LayoutComponentLoadingPreview.row,
    ),
    GalleryComponentDescriptor(
      id: 'manga-universe-map',
      className: 'MangaUniverseMapCard',
      label: 'Carte des univers',
      category: 'MANGA & LECTURE',
      description: 'Mondes et connexions',
      renderer: GalleryComponentFamily.mangaUniverse,
      loadingPreview: LayoutComponentLoadingPreview.row,
    ),
    GalleryComponentDescriptor(
      id: 'manga-status',
      className: 'MangaStatusCard',
      label: 'Statuts de mangas',
      category: 'MANGA & LECTURE',
      description: 'En cours, Terminé, En pause…',
      renderer: GalleryComponentFamily.mangaStats,
      loadingPreview: LayoutComponentLoadingPreview.row,
    ),
    GalleryComponentDescriptor(
      id: 'manga-serialization',
      className: 'MangaSerializationCard',
      label: 'Sérialisations',
      category: 'MANGA & LECTURE',
      description: 'Magazines de prépublication',
      renderer: GalleryComponentFamily.mangaStats,
      loadingPreview: LayoutComponentLoadingPreview.row,
    ),
    GalleryComponentDescriptor(
      id: 'manga-frequency',
      className: 'MangaFrequencyCard',
      label: 'Fréquence de sortie',
      category: 'MANGA & LECTURE',
      description: 'Chapitres sortant par période',
      renderer: GalleryComponentFamily.mangaStats,
      loadingPreview: LayoutComponentLoadingPreview.row,
    ),
    GalleryComponentDescriptor(
      id: 'manga-global-stats',
      className: 'MangaGlobalStatsCard',
      label: 'Statistiques globales',
      category: 'MANGA & LECTURE',
      description: 'Chiffres clés de la communauté',
      renderer: GalleryComponentFamily.mangaStats,
      loadingPreview: LayoutComponentLoadingPreview.row,
    ),
    GalleryComponentDescriptor(
      id: 'manga-popularity',
      className: 'MangaPopularityCard',
      label: 'Popularité & Tendances',
      category: 'MANGA & LECTURE',
      description: 'Mangas les plus populaires (+%)',
      renderer: GalleryComponentFamily.mangaStats,
      loadingPreview: LayoutComponentLoadingPreview.row,
    ),
    GalleryComponentDescriptor(
      id: 'manga-followers',
      className: 'MangaFollowersCard',
      label: 'Suiveurs / Abonnés',
      category: 'MANGA & LECTURE',
      description: 'Posters + compteurs de followers',
      renderer: GalleryComponentFamily.mangaStats,
      loadingPreview: LayoutComponentLoadingPreview.row,
    ),
    GalleryComponentDescriptor(
      id: 'manga-item-stats',
      className: 'MangaItemStatsCard',
      label: 'Statistiques par manga',
      category: 'MANGA & LECTURE',
      description: 'Détails complets d\\',
      renderer: GalleryComponentFamily.mangaStats,
      loadingPreview: LayoutComponentLoadingPreview.row,
    ),
    GalleryComponentDescriptor(
      id: 'manga-stats-grid',
      className: 'MangaStatsGridCard',
      label: 'Grille des statistiques',
      category: 'MANGA & LECTURE',
      description: 'Vue d\\',
      renderer: GalleryComponentFamily.mangaStats,
      loadingPreview: LayoutComponentLoadingPreview.row,
    ),
    GalleryComponentDescriptor(
      id: 'manga-category-ranking',
      className: 'MangaCategoryRankingCard',
      label: 'Classements par catégorie',
      category: 'MANGA & LECTURE',
      description: 'Populaire, note, nouveautés, followers',
      renderer: GalleryComponentFamily.mangaStats,
      loadingPreview: LayoutComponentLoadingPreview.row,
    ),
    GalleryComponentDescriptor(
      id: 'manga-reports',
      className: 'MangaReportsCard',
      label: 'Rapports & Aperçus',
      category: 'MANGA & LECTURE',
      description: 'Analyses et tendances',
      renderer: GalleryComponentFamily.mangaStats,
      loadingPreview: LayoutComponentLoadingPreview.row,
    ),
    GalleryComponentDescriptor(
      id: 'landscape-showcase',
      className: 'LandscapeShowcaseSection',
      label: 'Rail paysage générique',
      category: 'FILMS & SÉRIES · SECTIONS',
      description: 'Rail 16:9 paramétrable (titre + icône)',
      renderer: GalleryComponentFamily.landscape,
      loadingPreview: LayoutComponentLoadingPreview.landscape,
    ),
    GalleryComponentDescriptor(
      id: 'landscape-films',
      className: 'LandscapeFilmsSection',
      label: 'Films — À l’affiche',
      category: 'FILMS & SÉRIES · SECTIONS',
      description: 'Rail 16:9 des films du moment',
      renderer: GalleryComponentFamily.landscape,
      loadingPreview: LayoutComponentLoadingPreview.landscape,
    ),
    GalleryComponentDescriptor(
      id: 'landscape-series',
      className: 'LandscapeSeriesSection',
      label: 'Séries — Populaires',
      category: 'FILMS & SÉRIES · SECTIONS',
      description: 'Rail 16:9 des séries à la mode',
      renderer: GalleryComponentFamily.landscape,
      loadingPreview: LayoutComponentLoadingPreview.landscape,
    ),
    GalleryComponentDescriptor(
      id: 'landscape-manga',
      className: 'LandscapeMangaSection',
      label: 'Mangas — Coup de cœur',
      category: 'FILMS & SÉRIES · SECTIONS',
      description: 'Rail 16:9 des mangas appréciés',
      renderer: GalleryComponentFamily.landscape,
      loadingPreview: LayoutComponentLoadingPreview.landscape,
    ),
    GalleryComponentDescriptor(
      id: 'landscape-novels',
      className: 'LandscapeNovelsSection',
      label: 'Novels — Recommandés',
      category: 'FILMS & SÉRIES · SECTIONS',
      description: 'Rail 16:9 des novels à lire',
      renderer: GalleryComponentFamily.landscape,
      loadingPreview: LayoutComponentLoadingPreview.landscape,
    ),
    GalleryComponentDescriptor(
      id: 'landscape-playlist',
      className: 'LandscapePlaylistCard',
      label: 'Musique — Playlists',
      category: 'FILMS & SÉRIES · SECTIONS',
      description: 'Playlists pour accompagner le visionnage',
      renderer: GalleryComponentFamily.landscape,
      loadingPreview: LayoutComponentLoadingPreview.landscape,
    ),
    GalleryComponentDescriptor(
      id: 'landscape-genre-row',
      className: 'LandscapeGenreRow',
      label: 'Découvertes par genre',
      category: 'FILMS & SÉRIES · SECTIONS',
      description: 'Tuiles genre 16:9 compactes',
      renderer: GalleryComponentFamily.landscape,
      loadingPreview: LayoutComponentLoadingPreview.landscape,
    ),
    GalleryComponentDescriptor(
      id: 'home-hero-banner',
      className: 'HomeHeroBannerCard',
      label: 'Héros d\\',
      category: 'ACCUEIL & LECTURE',
      description: 'Bannière héros pleine largeur avec actions',
      renderer: GalleryComponentFamily.homeHero,
      loadingPreview: LayoutComponentLoadingPreview.hero,
    ),
    GalleryComponentDescriptor(
      id: 'home-spotlight-rail',
      className: 'HomeSpotlightRailCard',
      label: 'À ne pas manquer',
      category: 'ACCUEIL & LECTURE',
      description: 'Rail vertical compact de mises en avant',
      renderer: GalleryComponentFamily.homeHero,
      loadingPreview: LayoutComponentLoadingPreview.hero,
    ),
    GalleryComponentDescriptor(
      id: 'home-genre-tile',
      className: 'HomeGenreTileCard',
      label: 'Cartes de genres',
      category: 'ACCUEIL & LECTURE',
      description: 'Genres avec visuel carré et tagline',
      renderer: GalleryComponentFamily.homeHero,
      loadingPreview: LayoutComponentLoadingPreview.hero,
    ),
    GalleryComponentDescriptor(
      id: 'home-popular-rail',
      className: 'HomePopularRailCard',
      label: 'Populaire à regarder',
      category: 'ACCUEIL & LECTURE',
      description: 'Rail posters films/séries du moment',
      renderer: GalleryComponentFamily.homeHero,
      loadingPreview: LayoutComponentLoadingPreview.hero,
    ),
    GalleryComponentDescriptor(
      id: 'home-read-rail',
      className: 'HomeReadRailCard',
      label: 'Populaire à lire',
      category: 'ACCUEIL & LECTURE',
      description: 'Rail posters manga & novel',
      renderer: GalleryComponentFamily.homeHero,
      loadingPreview: LayoutComponentLoadingPreview.hero,
    ),
    GalleryComponentDescriptor(
      id: 'home-language-grid',
      className: 'HomeLanguageGridCard',
      label: 'Univers par pays',
      category: 'ACCUEIL & LECTURE',
      description: 'Puces de pays / langue',
      renderer: GalleryComponentFamily.homeHero,
      loadingPreview: LayoutComponentLoadingPreview.hero,
    ),
    GalleryComponentDescriptor(
      id: 'home-my-list',
      className: 'HomeMyListCard',
      label: 'Ma liste',
      category: 'ACCUEIL & LECTURE',
      description: 'Favoris en tuiles paysage',
      renderer: GalleryComponentFamily.homeHero,
      loadingPreview: LayoutComponentLoadingPreview.hero,
    ),
    GalleryComponentDescriptor(
      id: 'home-airecommender',
      className: 'HomeAIRecommenderCard',
      label: 'Recommandations IA',
      category: 'ACCUEIL & LECTURE',
      description: 'Saisie de suggestion personnalisée',
      renderer: GalleryComponentFamily.homeHero,
      loadingPreview: LayoutComponentLoadingPreview.hero,
    ),
    GalleryComponentDescriptor(
      id: 'home-mini-player',
      className: 'HomeMiniPlayerCard',
      label: 'Mini-lecteur de reprise',
      category: 'ACCUEIL & LECTURE',
      description: 'Reprendre la lecture en bas d\\',
      renderer: GalleryComponentFamily.homeHero,
      loadingPreview: LayoutComponentLoadingPreview.hero,
    ),
    GalleryComponentDescriptor(
      id: 'poster',
      className: 'PosterCard',
      label: 'Poster contenu',
      category: 'CATALOGUE & DISCOVERY',
      description: 'Rails catalogue',
      renderer: GalleryComponentFamily.posterRail,
      loadingPreview: LayoutComponentLoadingPreview.row,
    ),
    GalleryComponentDescriptor(
      id: 'poster-card-compact',
      className: 'PosterCard(compact)',
      label: 'Poster compact',
      category: 'CATALOGUE & DISCOVERY',
      description: 'Grille multi-rangées',
      renderer: GalleryComponentFamily.posterRail,
      loadingPreview: LayoutComponentLoadingPreview.row,
    ),
    GalleryComponentDescriptor(
      id: 'landscape',
      className: 'LandscapeCard',
      label: 'Carte paysage',
      category: 'CATALOGUE & DISCOVERY',
      description: 'Rails paysage',
      renderer: GalleryComponentFamily.landscape,
      loadingPreview: LayoutComponentLoadingPreview.landscape,
    ),
    GalleryComponentDescriptor(
      id: 'ranked-card',
      className: 'RankedCard',
      label: 'Carte classée',
      category: 'CATALOGUE & DISCOVERY',
      description: 'Classements',
      renderer: GalleryComponentFamily.ranked,
      loadingPreview: LayoutComponentLoadingPreview.ranked,
    ),
    GalleryComponentDescriptor(
      id: 'discovery',
      className: 'DiscoveryCard',
      label: 'Poster découverte',
      category: 'CATALOGUE & DISCOVERY',
      description: 'Rails découverte',
      renderer: GalleryComponentFamily.posterRail,
      loadingPreview: LayoutComponentLoadingPreview.row,
    ),
    GalleryComponentDescriptor(
      id: 'animated-discovery',
      className: 'AnimatedDiscoveryCard',
      label: 'Poster animé',
      category: 'CATALOGUE & DISCOVERY',
      description: 'Entrée animée',
      renderer: GalleryComponentFamily.posterRail,
      loadingPreview: LayoutComponentLoadingPreview.row,
    ),
    GalleryComponentDescriptor(
      id: 'ranked-discovery',
      className: 'RankedDiscoveryCard',
      label: 'Classée découverte',
      category: 'CATALOGUE & DISCOVERY',
      description: 'Classements',
      renderer: GalleryComponentFamily.ranked,
      loadingPreview: LayoutComponentLoadingPreview.ranked,
    ),
    GalleryComponentDescriptor(
      id: 'landscape-discovery',
      className: 'LandscapeDiscoveryCard',
      label: 'Paysage découverte',
      category: 'CATALOGUE & DISCOVERY',
      description: 'Rails sorties',
      renderer: GalleryComponentFamily.landscape,
      loadingPreview: LayoutComponentLoadingPreview.landscape,
    ),
    GalleryComponentDescriptor(
      id: 'featured-discovery',
      className: 'FeaturedDiscoveryCard',
      label: 'Carte mise en avant',
      category: 'CATALOGUE & DISCOVERY',
      description: 'Premier élément des rails tendance',
      renderer: GalleryComponentFamily.posterRail,
      loadingPreview: LayoutComponentLoadingPreview.row,
    ),
    GalleryComponentDescriptor(
      id: 'saga-discovery',
      className: 'SagaDiscoveryCard',
      label: 'Carte saga',
      category: 'CATALOGUE & DISCOVERY',
      description: 'Franchises et longues séries',
      renderer: GalleryComponentFamily.posterRail,
      loadingPreview: LayoutComponentLoadingPreview.row,
    ),
    GalleryComponentDescriptor(
      id: 'spotlight-discovery',
      className: 'SpotlightDiscoveryCard',
      label: 'Carte spotlight',
      category: 'CATALOGUE & DISCOVERY',
      description: 'Rail Coup de cœur',
      renderer: GalleryComponentFamily.posterRail,
      loadingPreview: LayoutComponentLoadingPreview.row,
    ),
    GalleryComponentDescriptor(
      id: 'tag',
      className: 'TagCard',
      label: 'Carte tag',
      category: 'CATALOGUE & DISCOVERY',
      description: 'Grilles de tags',
      renderer: GalleryComponentFamily.posterRail,
      loadingPreview: LayoutComponentLoadingPreview.row,
    ),
    GalleryComponentDescriptor(
      id: 'app-genre-tile',
      className: 'AppGenreTile',
      label: 'Tuile genre',
      category: 'CATALOGUE & DISCOVERY',
      description: 'Tuiles de genres',
      renderer: GalleryComponentFamily.mangaGenre,
      loadingPreview: LayoutComponentLoadingPreview.categoryPills,
    ),
    GalleryComponentDescriptor(
      id: 'media-ranked',
      className: 'MediaRankedRail',
      label: 'Classement horizontal',
      category: 'EXTENSIONS WATCH',
      description: 'Layouts ranked · rankedWide',
      renderer: GalleryComponentFamily.ranked,
      loadingPreview: LayoutComponentLoadingPreview.ranked,
    ),
    GalleryComponentDescriptor(
      id: 'media-landscape',
      className: 'MediaLandscapeRail',
      label: 'Carte showcase',
      category: 'EXTENSIONS WATCH',
      description: 'Layouts showcase · landscapeStacked',
      renderer: GalleryComponentFamily.landscape,
      loadingPreview: LayoutComponentLoadingPreview.landscape,
    ),
    GalleryComponentDescriptor(
      id: 'media-grid',
      className: 'MediaGridSection',
      label: 'Catégorie extension',
      category: 'EXTENSIONS WATCH',
      description: 'Layouts category · categoryPills',
      renderer: GalleryComponentFamily.collections,
      loadingPreview: LayoutComponentLoadingPreview.collections,
    ),
    GalleryComponentDescriptor(
      id: 'manga-featured',
      className: 'MangaFeaturedCard',
      label: 'Vedette manga',
      category: 'MANGA & LECTURE',
      description: 'Rail "À la une" du home manga',
      renderer: GalleryComponentFamily.homeHero,
      loadingPreview: LayoutComponentLoadingPreview.hero,
    ),
    GalleryComponentDescriptor(
      id: 'manga-resume',
      className: 'MangaResumeCard',
      label: 'Reprise de lecture',
      category: 'MANGA & LECTURE',
      description: 'Section "Reprendre la lecture"',
      renderer: GalleryComponentFamily.homeHero,
      loadingPreview: LayoutComponentLoadingPreview.hero,
    ),
    GalleryComponentDescriptor(
      id: 'manga-spotlight',
      className: 'MangaSpotlightCard',
      label: 'Spotlight manga',
      category: 'MANGA & LECTURE',
      description: 'Hero du home manga',
      renderer: GalleryComponentFamily.homeHero,
      loadingPreview: LayoutComponentLoadingPreview.hero,
    ),
    GalleryComponentDescriptor(
      id: 'manga-genre',
      className: 'MangaGenreCard',
      label: 'Genre manga',
      category: 'MANGA & LECTURE',
      description: 'Rail "Genres" du home manga',
      renderer: GalleryComponentFamily.mangaGenre,
      loadingPreview: LayoutComponentLoadingPreview.categoryPills,
    ),
    GalleryComponentDescriptor(
      id: 'manga-update-row',
      className: 'MangaUpdateRow',
      label: 'Ligne mise à jour',
      category: 'MANGA & LECTURE',
      description: 'Liste "Dernières mises à jour"',
      renderer: GalleryComponentFamily.homeHero,
      loadingPreview: LayoutComponentLoadingPreview.hero,
    ),
    GalleryComponentDescriptor(
      id: 'manga-banner',
      className: 'MangaBannerCard',
      label: 'Bannière manga',
      category: 'MANGA & LECTURE',
      description: 'Section pleine largeur du home manga',
      renderer: GalleryComponentFamily.homeHero,
      loadingPreview: LayoutComponentLoadingPreview.hero,
    ),
    GalleryComponentDescriptor(
      id: 'manga-top3',
      className: 'MangaTop3Card',
      label: 'Top 3 manga',
      category: 'MANGA & LECTURE',
      description: 'Rail "Top 3" triptyque',
      renderer: GalleryComponentFamily.ranked,
      loadingPreview: LayoutComponentLoadingPreview.ranked,
    ),
    GalleryComponentDescriptor(
      id: 'manga-latest-update',
      className: 'MangaLatestUpdateCard',
      label: 'Mise à jour chapitres',
      category: 'MANGA & LECTURE',
      description: 'Feed "Latest Chapter Updates"',
      renderer: GalleryComponentFamily.homeHero,
      loadingPreview: LayoutComponentLoadingPreview.hero,
    ),
    GalleryComponentDescriptor(
      id: 'manga-ranking',
      className: 'MangaRankingCard',
      label: 'Top Ranking manga',
      category: 'MANGA & LECTURE',
      description: 'Classement Daily / Weekly / Monthly',
      renderer: GalleryComponentFamily.ranking,
      loadingPreview: LayoutComponentLoadingPreview.ranked,
    ),
    GalleryComponentDescriptor(
      id: 'manga-vote',
      className: 'MangaVoteCard',
      label: 'Vote communautaire',
      category: 'MANGA & LECTURE',
      description: 'Carte vote type "Goonable tiers"',
      renderer: GalleryComponentFamily.homeHero,
      loadingPreview: LayoutComponentLoadingPreview.hero,
    ),
    GalleryComponentDescriptor(
      id: 'manga-collection-showcase',
      className: 'MangaCollectionShowcaseCard',
      label: 'Collection communautaire',
      category: 'MANGA & LECTURE',
      description: 'Collage + titre + stats + auteur',
      renderer: GalleryComponentFamily.homeHero,
      loadingPreview: LayoutComponentLoadingPreview.hero,
    ),
    GalleryComponentDescriptor(
      id: 'manga-trending-list',
      className: 'MangaTrendingListCard',
      label: 'Liste tendance',
      category: 'MANGA & LECTURE',
      description: 'Badge #N · TRENDING + rail de vote',
      renderer: GalleryComponentFamily.ranking,
      loadingPreview: LayoutComponentLoadingPreview.ranked,
    ),
    GalleryComponentDescriptor(
      id: 'manga-scan-group',
      className: 'MangaScanGroupCard',
      label: 'Groupe de scan',
      category: 'MANGA & LECTURE',
      description: 'Classement groupes · followers / titles / staff',
      renderer: GalleryComponentFamily.homeHero,
      loadingPreview: LayoutComponentLoadingPreview.hero,
    ),
    GalleryComponentDescriptor(
      id: 'three-column-swipe',
      className: 'ThreeColumnSwipeSection',
      label: 'Swipe 3 × 3',
      category: 'SECTIONS RÉUTILISABLES',
      description: '3 colonnes × 3 lignes, pagination horizontale',
      renderer: GalleryComponentFamily.swipe,
      loadingPreview: LayoutComponentLoadingPreview.row,
    ),
  ];
  static final Map<String, GalleryComponentDescriptor> _byId = {
    for (final descriptor in descriptors) ...{
      descriptor.id: descriptor,
      for (final alias in descriptor.aliases) alias: descriptor,
    },
  };

  static GalleryComponentDescriptor? resolve(String id) => _byId[id];

  static bool supports(String id) => _byId.containsKey(id);

  static List<GalleryComponentDescriptor> forContext({bool selectableOnly = false}) =>
      List.unmodifiable(
        descriptors.where(
          (descriptor) => !selectableOnly || descriptor.selectable,
        ),
      );

  static List<String> get availableIds => _byId.keys.toList(growable: false);

  /// Descriptors grouped by category, preserving the catalog declaration order.
  static Map<String, List<GalleryComponentDescriptor>> byCategory({
    bool selectableOnly = false,
  }) {
    final grouped = <String, List<GalleryComponentDescriptor>>{};
    for (final descriptor in descriptors) {
      if (selectableOnly && !descriptor.selectable) continue;
      grouped.putIfAbsent(descriptor.category, () => []).add(descriptor);
    }
    return grouped;
  }
}
